### ISSUE TITLE
sql compilation error when generating embed_text function

### ISSUE THREAD

**Issue by Mugl3** [Snowflake-Labs/sfguide-text-embedding-snowpark-container-service#4]
```sql
create or replace function embed_text(input string)
    returns vector(float,768)
    language SQL
    as
    $$_unpack_binary_array(to_binary(_embed_to_base64(input), 'BASE64'))::vector(float,768)$$;
```

It seems that vector is not a supported return type for SQL. Using javascript as the language gives an error on inferencing. Using an object doesn't seem to work with SQL language type. Any ideas?

I did have to change the definition for the other function to be:

```sql
create or replace function _embed_to_base64(input string)
    returns string
    service=embed_text_service
    endpoint=endpoint
    max_batch_rows=4
    as '/embed';
```

as having no endpoint argument was causing SQL compilation errors too.

**Comment by sfc-gh-lmerrick** [comment]
Thank you for opening an issue!

### First problem

> It seems that vector is not a supported return type for SQL. Using javascript as the language gives an error on inferencing. Using an object doesn't seem to work with SQL language type. Any ideas?

The latest substantial commit ( a3b85387b1a89d05d65f80a9724815563bc65848 ) changed from `ARRAY` return type to `VECTOR` since most of the usage of this quickstart was by folks enrolled in the Private Preview of the new `VECTOR` datatype (the `VECTOR` datatype was announced during our SnowDay event last year as a Private Preview feature and is still in Private Preview today). Here's an excerpt of that change which you can see if you poke around the linked commit:

```diff
@@ -188,12 +196,12 @@ def deploy_service(
         """
     )
     embed_text_create_statement = dedent(
-        """
+        f"""
         create or replace function embed_text(input string)
-            returns array
+            returns vector(float,{embedding_dim})
             language SQL
             as
-            $$_unpack_binary_array(to_binary(_embed_to_base64(input), 'BASE64'))$$;
+            $$_unpack_binary_array(to_binary(_embed_to_base64(input), 'BASE64'))::vector(float,{embedding_dim})$$;
         """
     )
     _run_sql(connection, embed_to_base64_create_statement)
```

Until you have access to vectors (i.e. it goes to public preview and you enroll) you can undo this change and get a function that returns an array. If you don't have the option of using the native `VECTOR` datatype yet, you may also find it helpful to strip things down to `BINARY`, which will have a smaller storage footprint and is more performant when converting in a Javascript or Python UDF:

```sql
create or replace function embed_text(input string)
    returns array
    language SQL
    as
    $$_unpack_binary_array((to_binary(_embed_to_base64(input), 'BASE64'))$$;


create or replace function embed_text_to_binary(input string)
    returns binary
    language SQL
    as
    $$to_binary(_embed_to_base64(input), 'BASE64')$$;
```


### Second problem


> I did have to change the definition for the other function to be:
> 
> ```diff
> create or replace function _embed_to_base64(input string)
>     returns string
> -    service=embed_text_service!endpoint
> +   service=embed_text_service
> +   endpoint=endpoint
>     max_batch_rows=4
>     as '/embed';
> ```
> as having no endpoint argument was causing SQL compilation errors too.

Thanks for reporting this! Fun fact -- container services SQL used to have a different syntax when it was in development, and this quickstart was apparently not fully updated when the syntax changed (I personally just had to [check the docs](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/working-with-services#service-functions-using-a-service-from-an-sql-query) to catch up).

If you would like the credit of fixing this syntax upstream in this repository, please open a PR and I will approve it. Otherwise I am happy to implement the fix myself. Please just let me know!

**Comment by Mugl3** [comment]
Thanks a lot for your prompt response. Our organisation is investigating using vectors soon, am very interested on seeing the benefits it offers. 
I made that PR at https://github.com/Snowflake-Labs/sfguide-text-embedding-snowpark-container-service/pull/5
Thanks for any feedback

**Comment by sfc-gh-lmerrick** [comment]
#5 is merged!

Let me know if the above suggestions around return type helped. If you're still waiting on `VECTOR` datatype, you may need to also define more of your own functions for operations like vector similarity search.

Here's a Javascript example of dot-product similarity on vectors stored as `BINARY` as a UDF (this should  be pretty fast on as many as 10k-100k vectors, though the built-in function currently in Private Preview will probably be a bit faster):

```sql
create or replace function dot_product(b1 binary, b2 binary)
returns float
language javascript
as
$$
v1 = new Float32Array(B1.buffer);
v2 = new Float32Array(B2.buffer);
return v1.reduce((running_total, v1_at_i, i)=>running_total + v1_at_i * v2[i] , 0)
$$;
```

I'm going to mark the issue as resolved for now, but please just chime in if you are still experiencing issues and I will reopen and assist!
